config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :order_forms
  resources :customers
  resources :orders
  get '/customers/index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get '/auth/failure' => 'sessions#failure'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    has_many :order_forms, dependent: :destroy, inverse_of: :customer
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :order_form, foreign_key: 'order_form_id'
    
    validates :quantity, numericality: {
        only_integer: true,
        greater_than_or_equal_to: 1,
        less_than_or_equal_to: 99 }
    
    validate :has_date_or_title
    def has_date_or_title
        errors.add(:title, :blank, message: "タイトルか日付は必須です") if date.blank? && title.blank?
        errors.add(:date, :blank, message: "タイトルか日付は必須です") if date.blank? && title.blank?
    end
end

app/models/order_form.rb
class OrderForm < ActiveRecord::Base
    has_many :orders, dependent: :destroy, inverse_of: :order_form
    belongs_to :customer
    accepts_nested_attributes_for :orders, allow_destroy: true
    
    validates_presence_of :orders
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        @q = Customer.search(params[:q])
        @customers = @q.result(distinct: true)
    end   
    
    def new
        @customer = Customer.new
    end
    
    def create
        
    end
    
    def update
        @customer = Customer.find(params[:id])
        @customer.update(customer_params)
        if @customer.save
            redirect_to root_path , notice: '注文書を保存しました'
        else
            redirect_to request.referrer , alert: '注文書の保存に失敗しました' 
        end
    end
    
    def show
        @customer = Customer.find_by_id(params[:id]) if params[:id]
        redirect_to request.referrer unless @customer
    end
  
    private
    
    def customer_params
        params.require(:customer).permit(:order_form, order_forms_attributes: [:id, :order_date, :orders, :_destroy])
    end
end

app/controllers/order_forms_controller.rb
class OrderFormsController < ApplicationController
  def new
    @customer = Customer.find_by_id(params[:customer_id])
    @order_form = @customer.order_forms.build
  end
  
  def create
    @order_form = OrderForm.new(order_form_params)
    if @order_form.save
      redirect_to root_path , notice: '注文書を保存しました'
    else
      # メッセージが保存できなかった時
      flash.now[:alert] = "注文書の保存に失敗しました。"
      render 'visitors/index'
    end
  end
  
  def order_form_params
    params.require(:order_form).permit(:order_date, :customer_id, orders_attributes: [:id, :title, :date, :quantity, :_destroy])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_forms_helper.rb
module OrderFormsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/index.html.erb
<h1>顧客情報の検索</h1>

<%= search_form_for @q do |f| %>

  <%# 名前から検索 %>
  <%= f.label :name_cont, "名前" %>
  <%= f.search_field :name_cont %>
  <br />

  <%# 検索ボタン %>
  <%= f.button :submit, :class=>'btn-primary' %>

<% end %>

<div class="container">
    <table class="table">
        <thead>
      <tr>
        <th>#</th>
        <th>名前</th>
        </th>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each.with_index(1) do |customer, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= customer.name %></td>
        <td><%= link_to '顧客情報を表示', customer_path(customer) %></td>
        <td><%= link_to '注文書を作成', new_order_form_path(customer_id: customer.id) %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
</div>

app/views/customers/show.html.erb
<h1><%= @customer.name %>の顧客情報</h1>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% if user_signed_in? %>
        <p class="navbar-text"><%= current_user.name %>でログインしています</p>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sales Management" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sales Management" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
       
      <div id="wrapper">
          <%= render 'shared/sidebar' %>
          <!-- Page Content -->
          <div id="page-content-wrapper">
              <div class="container-fluid">
                  <div class="row">
                      <div class="col-lg-12">
                        <%= yield %>
                      </div>
                  </div>
              </div>
          </div>
          <!-- /#page-content-wrapper -->
      </div>
      <!-- /#wrapper -->
                  
      <!-- Menu Toggle Script -->
      <script>
        $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
        });
      </script>
 
    </main>
  </body>
</html>

app/views/order_forms/_form.html.erb
  <%= @customer.name %>
  <div id='order_forms'>
      <%= simple_form_for @order_form do |order_form| %>
          <%= render 'order_form_fields', f: order_form %>
      <% end %>
  </div>

app/views/order_forms/_order_fields.html.erb
<div class='nested-fields'>
    <div class='order'>
        <%= f.input :title %>
        <%= f.input :date, include_blank: true %>
        <%= f.input :quantity, input_html: { value: 1, min: 1, max: 99, class: "quantity" } %>
        <%= link_to_remove_association '削除', f %>
    </div>
</div>

app/views/order_forms/_order_form_fields.html.erb
    <%= f.input :order_date %>
    <%= f.hidden_field :customer_id %>
    <div id='orders'>
        <%= f.simple_fields_for :orders do |order| %>
          <%= render 'order_fields', f: order %>
        <% end %>
        <div class='links'>
            <%= link_to_add_association '注文を追加', f, :orders %>
        </div>
    </div>
    <%= f.button :submit %>
    

app/views/order_forms/new.html.erb
<h1>注文書の新規作成</h1>
<%= render 'form' %>

app/views/orders/index.html.erb
<div class="container">
    <table class="table">
        <thead>
      <tr>
        <th>#</th>
        <th>顧客名</th>
        <th>タイトル</th>
        <th>メッセージ日付</th>
        <th>数量</th>
        <th>注文受付日</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each.with_index(1) do |order, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <% if order.order_form.customer != nil %>
          <td><%= order.order_form.customer.name %></td>
        <% else %>
          <td>不明な顧客</td>
        <% end %>
        <td><%= order.title %></td>
        <td><%= order.date %></td>
        <td><%= order.quantity %></td>
        <td><%= order.order_form.order_date %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
</div>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="#">
                Start Bootstrap
            </a>
        </li>
        <li>
            <%= link_to '注文書を作成', new_order_form_path %>
        </li>
        <li>
            <%= link_to '顧客情報を検索', customers_path %>
        </li>
        <li>
            <%= link_to '注文状況を見る', orders_path %>
        </li>
        <li>
            <a href="#">Events</a>
        </li>
        <li>
            <a href="#">About</a>
        </li>
        <li>
            <a href="#">Services</a>
        </li>
        <li>
            <a href="#">Contact</a>
        </li>
    </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/visitors/index.html.erb
<h1>Simple Sidebar</h1>
<p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
<p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
<a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>